config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pages do
    resources :comments
  end

  root "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :page
  belongs_to :user
end

app/models/page.rb
class Page < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_attached_file :image, styles: { :medium => "400x400#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pages
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @page = Page.find(params[:page_id])
    @comment = @page.comments.create(params[:comment].permit(:comment))
    @comment.user_id = current_user.id if current_user
    @comment.save

    if @comment.save
      redirect_to page_path(@page)
    else
      render 'new'
    end
  end

  def edit
    @page = Page.find(params[:page_id])
    @comment = @page.comments.find(params[:id])
  end

  def update
    @page = Page.find(params[:page_id])
    @comment = @page.comments.find(params[:id])

    if @comment.update(params[:comment].permit(:comment))
      redirect_to page_path(@page)
    else
      render 'edit'
    end
  end

  def destroy
    @page = Page.find(params[:page_id])
    @comment = @page.comments.find(params[:id])
    @comment.destroy
    redirect_to page_path(@page)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :find_page, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @page = Page.all.order("created_at DESC").paginate(page: params[:page], per_page: 6)
  end

  def show

  end

  def new
    @page = current_user.pages.build
  end

  def create
    @page = current_user.pages.build(page_params)
    if @page.save
      redirect_to @page, notice: 'Successfully creating new page'
    end
  end

  def update
    if @page.update(page_params)
      redirect_to @page
    else
      render 'edit'
    end
  end

  def destroy
    @page.destroy
    redirect_to root_path, notice: 'Successfully deleted page'
  end
  
  

  private

  def page_params
    params.require(:page).permit(:title, :description, :information, :image)
  end

  def find_page
    @page = Page.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/comments/_comment.html.haml
.comment.clearfix
  .content
    %p.comment_content= comment.comment
    %p.comment_author= comment.user.email
  .buttons
    = link_to "Edit", edit_page_comment_path(comment.page, comment)
    = link_to "Delete", [comment.page, comment], method: :delete, data: { confirm: "Are you sure?" }

app/views/comments/_form.html.haml
= simple_form_for([@page, @page.comments.build]) do |f|
  = f.input :comment
  = f.submit

app/views/comments/edit.html.haml
%h1 Edit Reply

= simple_form_for([@page, @comment]) do |f|
  = f.input :comment
  = f.submit

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title Bonstick2Bitcoin
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

%body
  %nav.navbar.navbar-default
    .container
      .navbar-brand= link_to "Bonstick2Bitcoin", root_path

      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "New page", new_page_path
          %li= link_to "Sign Out", destroy_user_session_path, method: :delete
      - else
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Sign Up", new_user_registration_path
          %li= link_to "Sign In", new_user_session_path


  .container
    - flash.each do |name, msg|
      = content_tag :div, msg, class: "alert"

    = yield

app/views/pages/_form.html.haml
= simple_form_for @page, html: { multipart: true } do |f|
  - if @page.errors.any?
    #errors
      %p
        = @page.errors.count
        Prevented this page froms saving
      %ul
        - @page.errors.full_messages.each do |msg|
          %li= msg
  .panel-body
    = f.input :title, input_html: { class: 'form-control' }
    = f.input :description, input_html: { class: 'form-control' }
    = f.input :information, input_html: { class: 'form-control' }
    = f.input :image, input_html: { class: 'form-control' }

  = f.button :submit , class: 'btn btn-primary'

app/views/pages/edit.html.haml
%h1 Edit Page

=render 'form'

app/views/pages/index.html.haml
- @page.each_slice(3) do |pages|
  .row
    - pages.each do |page|
      .col-md-4
        .page
          .image_wrapper
            = link_to page do
              = image_tag page.image.url(:medium)
          %h2= link_to page.title, page
= will_paginate @page, renderer: BootstrapPagination::Rails, previous_label: 'Previous', next_label: 'Next', inner_window:1, outer_window:0

app/views/pages/new.html.haml
%h1 New Page

= render 'form'

%br/

= link_to 'Back', root_path, class: 'btn btn-default'

app/views/pages/show.html.haml
= image_tag @page.image.url(:medium, class: 'page_image')
%h1= @page.title
%p= @page.description
%p= @page.information
%p Submitted by
%p= @page.user.email

#comments
  %h2
    = @page.comments.count
    Comments
  = render @page.comments

  %h3 Reply to thread
  = render "comments/form"

  %br/
  %hr/
  %br/

  = link_to "Edit", edit_page_path(@page), class: "button"
  = link_to "Delete", page_path(@page), method: :delete, data: { confirm: "Are you sure you want to do this?" }, class: "button"
  = link_to "Home", root_path